#!/bin/bash
# Change working directory to the project root since Lua include paths rely on it
cd "$(dirname "$0")"

function get_config {
	lua -e "c = require('config'); print(c.$1)"
}

function get_ip {
	# Echo is used to remove trailing whitespace
	echo $(hostname -I)
}

if [ "$1" == "logger" ]; then
	# Read IP from system
	ip=$(get_ip)

	# Extract port from the config file
	port=$(get_config 'logging.listener[2]');

	echo "Listening for messages on $ip:$port"
	netcat -ul "$port"
elif [ "$1" == "test" ]; then
	echo "Running unit tests"

	# Tests must be run within the context of the test folder
	cd tests
	#lua tests.lua -v
	lua tests.lua -o TAP
elif [ "$1" == "jenkins" ]; then
	echo "Running unit tests"

	# Tests must be run within the context of the test folder
	rm -f test_report.xml
	cd tests
	lua tests.lua -o JUNIT -n ../test_report.xml
elif [ "$1" == "doc" ]; then
	echo "Removing old documentation"
	rm -rf doc

	echo "Running LDoc"
	ldoc .
	sensible-browser doc/index.html &
elif [ "$1" == "install" ]; then
	echo "Installing necessary packages"
	sudo apt-get install lua5.1 lua-ldoc lua-discount love expect python-tftpy
elif [ "$1" == "export" ]; then
	# Read IP from system
	ip=$(get_ip)

	# Read box IP from config
	box_ip=$(get_config 'box_ip')

	echo "Packing local files"
	tar -cf build.tar start.lua config.lua lib/ data/ views/ components/

	echo "Starting TFTP server on $ip:9000"
	python -c 'import tftpy; s = tftpy.TftpServer("."); s.listen("0.0.0.0", 9000)' &
	tftp_pid="$!"

	echo "Connecting through telnet to set-top box at $box_ip"
	echo
	./backpack_upload_file $box_ip $ip build.tar
	echo
	echo

	echo "Killing TFTP server"
	kill $tftp_pid

	echo "Removing local file package"
	rm build.tar
elif [ "$1" == "lint" ]; then
	for file in $(find . -name '*.lua' ! -name 'serpent.lua' ! -name 'classy.lua' ! -name 'luaunit.lua'); do
		correct_count=$(grep -Pn $'^[\t]+[^\t ]' "$file"|wc -l)
		indented_count=$(grep -Pn $'^[\t ]+[^\t ]' "$file"|wc -l)

		incorrect_count=$(($indented_count - $correct_count))

		dots="................................................................."
		tput setf 5; echo -n "$file "; tput sgr0
		tput setf 1; echo -n "${dots:${#file}} "; tput sgr0


		if [ "$incorrect_count" -gt 0 ]; then
			tput setf 4; echo "ERROR"; tput sgr0
			tput setf 6; echo -e "\tSome lines were not correctly indented with tabs"; tput sgr0
		else
			tput setf 2; echo "OK"; tput sgr0
		fi
	done
elif [ "$1" == "fprint" ]; then
	dots="................................................................."
	for file in $(find . -name '*.lua' ! -name 'serpent.lua' ! -name 'classy.lua' ! -name 'luaunit.lua'); do
	if grep -q 'print(' $file; then
		tput setf 5; echo -n "$file "; tput sgr0
		tput setf 1; echo -n "${dots:${#file}} "; tput sgr0
		tput setf 4; echo "ERROR"; tput sgr0
		tput setf 6; echo -e "\tPrint found in file"
	fi
	done
elif [ "$1" == "ffreetype" ]; then
	dots="................................................................."
	for file in $(find . -name '*.lua' ! -name 'Font.lua' ! -name 'main.lua' ! -name 'sys.lua' ! -name 'SysMock.lua' ! -name 'freetype.lua' ! -name 'test_mock_FreetypeMock.lua' ! -name 'FreetypeMock.lua'); do
	if grep -q 'freetype' $file; then
		tput setf 5; echo -n "$file "; tput sgr0
		tput setf 1; echo -n "${dots:${#file}} "; tput sgr0
		tput setf 4; echo "ERROR"; tput sgr0
		tput setf 6; echo -e "\tFreetype found in file"
	fi
	done
elif [ "$1" == "run" -o "$1" == "" ]; then
	echo "Starting emulator"
	love .
else
	echo "Backpack application task runner"
	echo ""
	echo "Usage:"
	echo "	backpack [run]    Run application in emulator"
	echo "	backpack doc      Generate code documentation and open in browser"
	echo "	backpack export   Put code on USB memory on set-top box. Does not start"
	echo "	                  application"
	echo "	backpack install  Install required system packages (expert only)"
	echo "	backpack lint     Check files for poor indentation"
	echo "	backpack logger   Start listener for UDPLogger (on port in config.lua)"
	echo "	backpack jenkins  Run all unit tests to produce a XML file in JUnit"
	echo "	                  format"
	echo "	backpack test     Run all unit tests"
fi
