#!/usr/bin/expect
set timeout -1

set host [lindex $argv 0]
set remote [lindex $argv 1]
set file [lindex $argv 2]

spawn telnet $host

expect "/ #"
send "cd /mnt/*\n"

expect " # "
send "tftp -g -r $file $remote 9000\n"

expect " # "
send "tar -zxf build.tar.gz\n"

# Start application
expect -re "\n(.*?) # " {
	set location "$expect_out(1,string)"
}
send "ZacCmdClient\n"

expect "exit the application"
send "killapp LuaEngine\n"

expect "LuaEngine is killed" {
	sleep 1
} "Invalid operation" {
	sleep 1
}
send "startapp LuaEngine LuaEngine\n"

expect "LuaEngine is started"
sleep 2
send "SetInputPriority LuaEngine 10\n"
sleep 1
send "sendcmd LuaEngine run $location/start.lua\n"

expect "Sent command to LuaEngine"
