local MultipleQuestion= require("lib.quiz.MultipleChoiceQuestion")
mq1=MultipleQuestion("","",{1,2,3})
print(mq1:is_correct({1,2}))
print(mq1:get_correct_answers_number())
print(mq1:get_wrong_answers_number())
mq2=MultipleQuestion("","",{1,2,3})
print(mq2:is_correct({1,2,3,4}))
print(mq2:get_correct_answers_number())
print(mq2:get_wrong_answers_number())
