local City = require("lib.city")
-- @module attraction
local attractions = {}

attractions.attraction = { paris = {
                                    {name = "The Eiffel Tower",
                                    question = "How tall is the Eiffel Tower?",
                                    answers = {"324 metres", "564 metres", "137 metres", "401 metres"},
                                    pic_url = "data/images/CityTourEiffelTower.png",
                                    text = {"The Eiffel Tower is named after the engineer Gustave Eiffel, whose ",
                                            "company designed and built the tower. It was finished in 1889 and",
                                            "it is a global cultural icon of France and one of the most recognisable",
                                            "structures in the world. Around 6.98 million people visited the Eiffel",
                                            "Tower in 2011. The tower is 324 metres tall and Its base is 125 metres",
                                            "wide. The Eiffel Tower was the tallest man-made structure in the",
                                            "world for 41 years. Today it is the second-tallest structure in France.",
                                            " The tower has three levels for visitors, with restaurants on the first",
                                            "and second. The third level observatory's upper platform is 276 m",
                                            "above the ground. The climb from ground level to the first level is",
                                            "over 300 steps."}
                                  },
                                    {name = "Arc de Triomphe",
                                    question = "When was Arc de Triomphe finished?",
                                    answers = {"1836", "2001", "1993", "700"},
                                    pic_url = "data/images/CityTourArchDeTriomphe.png",
                                    text = {"One of the most famous monuments in Paris is called Arc de",
                                            "Triomphe. It was designed by Jean Chalgrin and built between 1806",
                                            "and 1836. Visitors can admire its delicate design and engravings.",
                                            "The monument is 50 meters 45 meters wide and 22 meters deep.",
                                            "The Arc de Triomphe provides a glimpse into France’s social past as",
                                            "well as spectacular views across central Paris. It has four",
                                            "mainsculptural groups on each pillar depicting Le Départ de 1792,",
                                            "Le Triomphe de 1810, La Résistance de 1814 and La Paix 1815. On",
                                            "inside of the arch pillars names of military leaders of the French",
                                            "Revolution and Empire are engraved."}
                                    },
                                    {name = "Les Invalides",
                                    question = "Who of the following is buried here?",
                                    answers = {"Napoleon Bonaparte", "Gustave Eiffel", "Jean Chalgrin", "Philippe Pétain"},
                                    pic_url = "data/images/CityTourLesInvalides.png",
                                    text = {"Les Invalides is officially known as L'Hôtel national des Invalides",
                                            "(The National Residence of the Invalids). It is a complex of buildings",
                                            "in the 7th arrondissement of Paris, France containing museums and",
                                            "monuments, all relating to the military history of France. It also",
                                            "contains a hospital and a retirement home for war veterans. The",
                                            "buildings house the Musée de l'Armée, the military museum of the Army",
                                            "of France, the Musée des Plans-Reliefs, and the Musée d'Histoire",
                                            "Contemporaine, as well as the Dôme des Invalides, a large church with",
                                            "the burial site for some of France's war heroes, most notably Napoleon",
                                            "Bonaparte. The architect of Les Invalides was Libéral Bruant. The",
                                            "project was initiated by Louise XIV in an order dated 24 November 1670,",
                                            "as a home and hospital for aged and unwell soldiers."}


                                  },
                                  {name = "Louvre",
                                  question = "The Louvre had a new entrance built in the main court of a glass pyraimd. When was it built?",
                                  answers = {"1968", "1978", "1988", "1998"},
                                  pic_url = "data/images/CityTourEiffelTower.png",
                                  text = {"The Louvre Palace or the Louvre Museum is one of the world's",
                                          "largest museums and a historic monument in Paris, France. Nearly",
                                          "35,000 objects from prehistory to the 21st century are exhibited over",
                                          "an area of 60,600 square meters (652,300 square feet). The Louvre is",
                                          "the world's most visited museum, receiving more than 9.7 million",
                                          "visitors in 2012. The museum opened on 10 August 1793 with an",
                                          "exhibition of 537 paintings, the majority of the works being royal",
                                          "and confiscated church property. Because of structural problems",
                                          "with the building, the museum was closed in 1796 until 1801. The",
                                          " collection was increased under Napoleon and the museum",
                                          "renamed the Musée Napoléon, but after Napoleon's abdication many",
                                          "works seized by his armies were returned to their original owners.",
                                          " The High Renaissance collection includes, Virgin and Child with ",
                                          "St. Anne, St. John the Baptist, and Madonna of the Rocks and The ",
                                          "Louvres most popular attraction, Leonardo da Vinci's Mona Lisa."
                                        }
                                  }
                              },
                              rio_de_janeiro = {
                                          {name = "The Eiffel Tower",
                                          question = "How tall is the Eiffel Tower?",
                                          answers = {"324 metres", "564 metres", "137 metres", "401 metres"},
                                          pic_url = "data/images/CityTourEiffelTower.png",
                                          text = {"The Eiffel Tower is named after the engineer Gustave Eiffel, whose ",
                                                  "company designed and built the tower. It was finished in 1889 and",
                                                  "it is a global cultural icon of France and one of the most recognisable",
                                                  "structures in the world. Around 6.98 million people visited the Eiffel",
                                                  "Tower in 2011. The tower is 324 metres tall and Its base is 125 metres",
                                                  "wide. The Eiffel Tower was the tallest man-made structure in the",
                                                  "world for 41 years. Today it is the second-tallest structure in France.",
                                                  " The tower has three levels for visitors, with restaurants on the first",
                                                  "and second. The third level observatory's upper platform is 276 m",
                                                  "above the ground. The climb from ground level to the first level is",
                                                  "over 300 steps."}
                                        },
                                          {name = "Arc de Triomphe",
                                          question = "How deep is the monument?",
                                          answers = {"45 metres", "22 metres", "10 metres", "30 metres"},
                                          pic_url = "data/images/CityTourEiffelTower.png",
                                          text = {"One of the most famous monuments in Paris is called Arc de",
                                                  "Triomphe. It was designed by Jean Chalgrin and built between 1806",
                                                  "and 1836. Visitors can admire its delicate design and engravings.",
                                                  "The monument is 50 meters 45 meters wide and 22 meters deep.",
                                                  "The Arc de Triomphe provides a glimpse into France’s social past as",
                                                  "well as spectacular views across central Paris. It has four",
                                                  "mainsculptural groups on each pillar depicting Le Départ de 1792,",
                                                  "Le Triomphe de 1810, La Résistance de 1814 and La Paix 1815. On",
                                                  "inside of the arch pillars names of military leaders of the French",
                                                  "Revolution and Empire are engraved."}
                                          },
                                          {name = "Les Invalides",
                                          question = "What is the monument related to?",
                                          answers = {"Military history", "Food history", "C4yourself history", "No history"},
                                          pic_url = "data/images/CityTourEiffelTower.png",
                                          text = {"Les Invalides is officially known as L'Hôtel national des Invalides (The National Residence of the Invalids). It is a complex of buildings in the 7th arrondissement of Paris, France containing museums and monuments, all relating to the military history of France. It also contains a hospital and a retirement home for war veterans. The buildings house the Musée de l'Armée, the military museum of the Army of France, the Musée des Plans-Reliefs, and the Musée d'Histoire Contemporaine, as well as the Dôme des Invalides, a large church with the burial site for some of France's war heroes, most notably Napoleon Bonaparte. The architect of Les Invalides was Libéral Bruant. The project was initiated by Louise XIV in an order dated 24 November 1670, as a home and hospital for aged and unwell soldiers."}
                                        }
                                      },

                            cairo = {
                                    {name = "The Eiffel Tower",
                                    pic_url = "data/images/CityTourEiffelTower.png",
                                    text = {"The Eiffel Tower is named after the engineer Gustave Eiffel, whose ",
                                        "company designed and built the tower. It was finished in 1889 and",
                                            "it is a global cultural icon of France and one of the most recognisable",
                                            "structures in the world. Around 6.98 million people visited the Eiffel",
                                            "Tower in 2011. The tower is 324 metres tall and Its base is 125 metres",
                                            "wide. The Eiffel Tower was the tallest man-made structure in the",
                                            "world for 41 years. Today it is the second-tallest structure in France.",
                                            " The tower has three levels for visitors, with restaurants on the first",
                                            "and second. The third level observatory's upper platform is 276 m",
                                            "above the ground. The climb from ground level to the first level is",
                                            "over 300 steps."}
                                  },
                                    {name = "Arc de Triomphe",
                                    pic_url = "data/images/CityTourEiffelTower.png",
                                    text = {"One of the most famous monuments in Paris is called Arc de",
                                            "Triomphe. It was designed by Jean Chalgrin and built between 1806",
                                            "and 1836. Visitors can admire its delicate design and engravings.",
                                            "The monument is 50 meters 45 meters wide and 22 meters deep.",
                                            "The Arc de Triomphe provides a glimpse into France’s social past as",
                                            "well as spectacular views across central Paris. It has four",
                                            "mainsculptural groups on each pillar depicting Le Départ de 1792,",
                                            "Le Triomphe de 1810, La Résistance de 1814 and La Paix 1815. On",
                                            "inside of the arch pillars names of military leaders of the French",
                                            "Revolution and Empire are engraved."}
                                    },
                                    {name = "Les Invalides",
                                    pic_url = "data/images/CityTourEiffelTower.png",
                                    text = {"Les Invalides is officially known as L'Hôtel national des Invalides (The National Residence of the Invalids). It is a complex of buildings in the 7th arrondissement of Paris, France containing museums and monuments, all relating to the military history of France. It also contains a hospital and a retirement home for war veterans. The buildings house the Musée de l'Armée, the military museum of the Army of France, the Musée des Plans-Reliefs, and the Musée d'Histoire Contemporaine, as well as the Dôme des Invalides, a large church with the burial site for some of France's war heroes, most notably Napoleon Bonaparte. The architect of Les Invalides was Libéral Bruant. The project was initiated by Louise XIV in an order dated 24 November 1670, as a home and hospital for aged and unwell soldiers."},
                                  }
                                },

                                    mumbai = {
                                          {name = "Gateway of India",
                                          question = "How high is the arch of the strucutre?",
                                          answers = {"26 metres", "32 metres", "50 metres", "15 metres"},
                                          pic_url = "data/images/CityTourEiffelTower.png",
                                          text = {"The Gateway of India is a monument built during the British Rule in",
                                                  "Mumbai City of Maharashtra state in Western India. The Gateway of India",
                                                  "was built to commemorate the visit of King George V and Queen Mary to",
                                                  "Mumbai, prior to the Delhi Durbar, in December 1911. However, they only",
                                                  "got to see a cardboard model of the structure since the construction",
                                                  "did not begin til 1915. It is located on the waterfron in the Apollo",
                                                  "Bunder area in South Mubai nad overlooks the Arabian sea. The structure",
                                                  "is a basalt arch, 26 metres (85 feet) high. It lies at the end of",
                                                  "Chhatrapati Shivaji Marg at the water's edge in Mumbai Harbor. It was",
                                                  "a crude jetty used by the fishing community which was later renovated",
                                                  "and used as a landing place for British governors and other prominent",
                                                  "people. In earlier times, it would have been the first structure that",
                                                  "visitors arriving by boat in Mumbai would have seen."
                                                  }
                                        },
                                          {name = "Haji Ali Mosque/mausoleum",
                                          question = "According to legends, Haji Ali once jabbed a finger into the soil making what gush out?",
                                          answers = {"Oil", "Gold", "Water", "Wine"},
                                          pic_url = "data/images/CityTourEiffelTower.png",
                                          text = {"The Haji Ali Dargah was constructed in 1431 in memory of a wealthy",
                                                  "Muslim merchant, Sayyed Peer Haji Ali Shah Bukhari, who gave up all",
                                                  "his worldly possessions before making a pilgrimage to Mecca. Hailing",
                                                  "from Bukhara, in present day Uzbekistan, Bukhari travelled around the",
                                                  "world in the early to mid 15th century, and eventually settled in",
                                                  "present day Mumbai. According to legends surrounding his life, he",
                                                  "once saw a poor woman crying on the road, holding an empty vessel. He",
                                                  "asked her what the problem was, she sobbed that her husband would",
                                                  "thrash her as she stumbled and accidentally spilled the oil she was",
                                                  "carrying. He asked her to take him to the spot where she spilt the",
                                                  "oil. There, he jabbed a finger into the soil and the oil gushed out.",
                                                  "The overjoyed woman filled up the vessel and went home. Haji Ali died",
                                                  "during his journey to Mecca and miraculously the casket carrying his",
                                                  "body, floated back to these shores, getting stuck in the string of",
                                                  "rocky islets just off the shore of Worli. Thus, the Dargah was",
                                                  "constructed there, on a tiny islet located 500 meters from the coast,",
                                                  "in the middle of Worli Bay."}
                                          },
                                          {name = "Chhatrapati Shivaju Terminus",
                                          question = "How many years did it take to build the station?",
                                          answers = {"10", "12", "8", "14"},
                                          pic_url = "data/images/CityTourEiffelTower.png",
                                          text = {"Chhatrapati Shivaji Terminus (previously Victoria Terminus) is a",
                                                  "UNESCO World Heritage historic railway station in Mumbai Maharashtra,",
                                                  "India which serves as the headquarters of the Central Railways. The",
                                                  "station took ten years to complete, the longest for any building of",
                                                  "that era in Bombay. Designed by Frederick William Stevens with",
                                                  "influences from Victorian Italianate Gothic Revival architecture",
                                                  "and traditional Mughal buildings, the station was built in 1887 in",
                                                  "the Bori Bunder area of Mumbai to commemorate the Golden Jubilee of",
                                                  "Queen Victoria. Stevens earned the commission to construct the station",
                                                  "after a masterpiece watercolor sketch by draughtsman Axel Haig. The new",
                                                  "railway station was built on the location of the Bori Bunder Station",
                                                  "and is one of the busiest railway stations in India"}

                                        },
                                          {name = "Taj Mahal Palace & Tower",
                                          pic_url = "data/images/CityTourEiffelTower.png",
                                          text = {"The Taj Mahal Palace Hotel is a five-star hotel located in the Colaba",
                                                  "region of Mumbai, Maharashtra,India, next to the Gateway of",
                                                  "India. The hotel's original building first opened its doors to guests",
                                                  "on 16 December 1903. Part of the Taj Hotels, Resorts and Palaces,",
                                                  "this hotel is considered the flagship property of the Tata group and",
                                                  "contains 560 rooms and 44 suites and 11 restaurants. From a",
                                                  "historical and architectural point of view, the two buildings that",
                                                  "make up the hotel, the Taj Mahal Palace and the Tower are two",
                                                  "distinct buildings, built at different times and in different",
                                                  "architectural designs."
                                              }
                                        }
                                      },

                                london = {
                                          {name = "The Eiffel Tower",
                                          question = "How tall is the Eiffel Tower?",
                                          answers = {"324 metres", "564 metres", "137 metres", "401 metres"},
                                          pic_url = "data/images/CityTourEiffelTower.png",
                                          text = {"The Eiffel Tower is named after the engineer Gustave Eiffel, whose ",
                                                  "company designed and built the tower. It was finished in 1889 and",
                                                  "it is a global cultural icon of France and one of the most recognisable",
                                                  "structures in the world. Around 6.98 million people visited the Eiffel",
                                                  "Tower in 2011. The tower is 324 metres tall and Its base is 125 metres",
                                                  "wide. The Eiffel Tower was the tallest man-made structure in the",
                                                  "world for 41 years. Today it is the second-tallest structure in France.",
                                                  " The tower has three levels for visitors, with restaurants on the first",
                                                  "and second. The third level observatory's upper platform is 276 m",
                                                  "above the ground. The climb from ground level to the first level is",
                                                  "over 300 steps."}
                                        },
                                          {name = "Arc de Triomphe",
                                          question = "How deep is the monument?",
                                          answers = {"45 metres", "22 metres", "10 metres", "30 metres"},
                                          pic_url = "data/images/CityTourEiffelTower.png",
                                          text = {"One of the most famous monuments in Paris is called Arc de",
                                                  "Triomphe. It was designed by Jean Chalgrin and built between 1806",
                                                  "and 1836. Visitors can admire its delicate design and engravings.",
                                                  "The monument is 50 meters 45 meters wide and 22 meters deep.",
                                                  "The Arc de Triomphe provides a glimpse into France’s social past as",
                                                  "well as spectacular views across central Paris. It has four",
                                                  "mainsculptural groups on each pillar depicting Le Départ de 1792,",
                                                  "Le Triomphe de 1810, La Résistance de 1814 and La Paix 1815. On",
                                                  "inside of the arch pillars names of military leaders of the French",
                                                  "Revolution and Empire are engraved."}
                                          },
                                          {name = "Les Invalides",
                                          question = "What is the monument related to?",
                                          answers = {"Military history", "Food history", "C4yourself history", "No history"},
                                          pic_url = "data/images/CityTourEiffelTower.png",
                                          text = {"Les Invalides is officially known as L'Hôtel national des Invalides (The National Residence of the Invalids). It is a complex of buildings in the 7th arrondissement of Paris, France containing museums and monuments, all relating to the military history of France. It also contains a hospital and a retirement home for war veterans. The buildings house the Musée de l'Armée, the military museum of the Army of France, the Musée des Plans-Reliefs, and the Musée d'Histoire Contemporaine, as well as the Dôme des Invalides, a large church with the burial site for some of France's war heroes, most notably Napoleon Bonaparte. The architect of Les Invalides was Libéral Bruant. The project was initiated by Louise XIV in an order dated 24 November 1670, as a home and hospital for aged and unwell soldiers."}
                                        }
                                      },


                                new_york = {
                                          {name = "The Eiffel Tower",
                                          question = "How tall is the Eiffel Tower?",
                                          answers = {"324 metres", "564 metres", "137 metres", "401 metres"},
                                          pic_url = "data/images/CityTourEiffelTower.png",
                                          text = {"The Eiffel Tower is named after the engineer Gustave Eiffel, whose ",
                                                  "company designed and built the tower. It was finished in 1889 and",
                                                  "it is a global cultural icon of France and one of the most recognisable",
                                                  "structures in the world. Around 6.98 million people visited the Eiffel",
                                                  "Tower in 2011. The tower is 324 metres tall and Its base is 125 metres",
                                                  "wide. The Eiffel Tower was the tallest man-made structure in the",
                                                  "world for 41 years. Today it is the second-tallest structure in France.",
                                                  " The tower has three levels for visitors, with restaurants on the first",
                                                  "and second. The third level observatory's upper platform is 276 m",
                                                  "above the ground. The climb from ground level to the first level is",
                                                  "over 300 steps."}
                                        },
                                          {name = "Arc de Triomphe",
                                          question = "How deep is the monument?",
                                          answers = {"45 metres", "22 metres", "10 metres", "30 metres"},
                                          pic_url = "data/images/CityTourEiffelTower.png",
                                          text = {"One of the most famous monuments in Paris is called Arc de",
                                                  "Triomphe. It was designed by Jean Chalgrin and built between 1806",
                                                  "and 1836. Visitors can admire its delicate design and engravings.",
                                                  "The monument is 50 meters 45 meters wide and 22 meters deep.",
                                                  "The Arc de Triomphe provides a glimpse into France’s social past as",
                                                  "well as spectacular views across central Paris. It has four",
                                                  "mainsculptural groups on each pillar depicting Le Départ de 1792,",
                                                  "Le Triomphe de 1810, La Résistance de 1814 and La Paix 1815. On",
                                                  "inside of the arch pillars names of military leaders of the French",
                                                  "Revolution and Empire are engraved."}
                                          },
                                          {name = "Les Invalides",
                                          question = "What is the monument related to?",
                                          answers = {"Military history", "Food history", "C4yourself history", "No history"},
                                          pic_url = "data/images/CityTourEiffelTower.png",
                                          text = {"Les Invalides is officially known as L'Hôtel national des Invalides (The National Residence of the Invalids). It is a complex of buildings in the 7th arrondissement of Paris, France containing museums and monuments, all relating to the military history of France. It also contains a hospital and a retirement home for war veterans. The buildings house the Musée de l'Armée, the military museum of the Army of France, the Musée des Plans-Reliefs, and the Musée d'Histoire Contemporaine, as well as the Dôme des Invalides, a large church with the burial site for some of France's war heroes, most notably Napoleon Bonaparte. The architect of Les Invalides was Libéral Bruant. The project was initiated by Louise XIV in an order dated 24 November 1670, as a home and hospital for aged and unwell soldiers."}
                                        }
                                      },

                                  tokyo = {
                                          {name = "Tokyo Skytree",
                                          question = "The Tokyo Skytree is the tallest building in Japan, how tall is it?",
                                          answers = {"634m (2080ft)", "645m (2116ft)", "673m (2208ft)", "643m (2109ft)"},
                                          pic_url = "data/images/CityTourEiffelTower.png",
                                          text = {"The Tokyo Skytree is a broadcasting, restaurant, and observation",
                                                  "tower in Tokyo, tallest structure in Japan in 2010 and reached",
                                                  "its full height of 634m (2080ft) in March 2011, making it the",
                                                  "tallest tower in the world, displacing the Canton Tower, and the",
                                                  "second tallest structure in the world after the Burj Khalifa",
                                                  "(830m/2722ft). It was completed on 29 February 2012, with the",
                                                  "tower opening to the public on 22 May 2012."}
                                        },
                                          {name = "Sensōji Temple",
                                          question = "What type of temple is Sensō-ji?",
                                          answers = {"A Buddhist Temple", "A Hindu Temple", "A Christian Temple", "A Muslim Temple"},
                                          pic_url = "data/images/CityTourEiffelTower.png",
                                          text = {"Sensō-ji is an ancient Buddhist temple located in Asakusa, Tokyo,",
                                                  "Japan. It is Tokyo's one of its most significant. Sensō-ji is the",
                                                  "focus of Tokyo's largest and most popular festival, Sanja Matsuri.",
                                                  "This takes place over 3–4 days in late spring, and sees the",
                                                  "surrounding streets closed to traffic from dawn until late evening.",
                                                  "Many tourists visit Sensō-ji every year, the surrounding area has",
                                                  "many traditional shops and eating places that feature traditional",
                                                  "dishes (hand-made noodles, sushi, tempura, etc.). During World",
                                                  "War II, the temple was bombed and destroyed. It was rebuilt later",
                                                  "and is a symbol of rebirth and peace to the Japanese people."}
                                          },

                                          {name = "Tokyo Disneyland",
                                          question = "How many themes does Tokyo Disneyland have?",
                                          answers = {"7", "8", "9", "10"},
                                          pic_url = "data/images/CityTourEiffelTower.png",
                                          text = {"Tokyo Disneyland is a 115-acre (47 ha) theme park at near Tokyo.",
                                                  "The park has seven themed areas: the World Bazaar; the four classic",
                                                  "Disney lands: Adventureland, Western land, Fantasyland and",
                                                  "Tomorrowland; and two mini-lands: Critter Country and Mickey's Toon",
                                                  "town. In 2013, Tokyo Disneyland hosted 17.2 million visitors, making",
                                                  "it the world's second-most visited theme park behind the Magic",
                                                  "Kingdom at Walt Disney World Resort."}
                                        }
                                      },

                                  sydney = {
                                          {name = "Sydney Opera House",
                                          question = "When was the building formally opened by Queen Elizaberg II?",
                                          answers = {"1973", "1975", "1983", "1979"},
                                          pic_url = "data/images/CityTourEiffelTower.png",
                                          text = {"the Sydney Opera House is a multi-venue performing arts center in",
                                                  "Sydney, Australia. It is situated on Bennelong Point in Sydney Harbor,",
                                                  "close to the Sydney Harbor Bridge, and adjacent to the Sydney central",
                                                  "business district and the Royal Botanic Gardens, between Sydney Cove",
                                                  "and Farm Cove. Designed by Danish architect Jørn Utzon, the building",
                                                  "was formally opened on 20 October 1973, by Queen Elizabeth Elizabeth II.",
                                                  "II. Though its name suggests a single venue, the building comprises",
                                                  "performance venues which together are among the busiest performing",
                                                  "arts centers in the world—hosting over 1,500 performances each year",
                                                  "attended by some 1.2 million people."}
                                        },
                                          {name = "Sydney Tower",
                                          question = "When did the Sydney Tower open for the public?",
                                          answers = {"1981", "1971", "1975", "1985"},
                                          pic_url = "data/images/CityTourEiffelTower.png",
                                          text = {"Sydney Tower is Sydney's tallest structure and the second tallest",
                                                  "observation tower in the Southern Hemisphere. The tower stands 309m",
                                                  "(1014ft) above the Sydney central business district, located on",
                                                  "Market Street, between Pitt and Castlereagh Streets. The tower is",
                                                  "open to the public, and is one of the most prominent tourist",
                                                  "attractions in the city, being visible from a number of vantage",
                                                  "points throughout town and from adjoining suburbs. Designed by",
                                                  "Australian architect Donald Crone the first plans for Sydney Tower",
                                                  "were unveiled in March 1968. Construction of the office building",
                                                  "commenced in 1970, and tower construction began in 1975. Public",
                                                  "access to the tower began in August 1981."}
                                          },
                                          {name = "The Queen Victoria Building",
                                          question = "When was the building finished?",
                                          answers = {"1898", "1893", "1891", "1885"},
                                          pic_url = "data/images/CityTourEiffelTower.png",
                                          text = {"The Queen Victoria Building (or QVB), is a late nineteenth-century",
                                                  "building architect George McRae in the central business district",
                                                  "of Sydney, Australia. The Romanesque Revival building was",
                                                  "constructed between 1893 and 1898 and is 30m (98ft) wide by 190m",
                                                  "(620ft) long. The building fills a city block bounded by George,",
                                                  "Market, York and Druitt Streets. Designed as a marketplace, it was",
                                                  "used for a variety of other purposes, underwent re-modelling and",
                                                  "suffered decay until its restoration and return to its original",
                                                  "use in the late twentieth century."}
                                        }


                                      },


                                  cairo = {
                                         {name = "Pyramid of Giza",
                                         question = "What is the Great Pyramid of Giza called?",
                                         answers = {"Pyramid of Cheops", "Pyramid of Pharao", "Pyramid of Cairo", "Pyramid of Egypt"},
                                         pic_url = "data/images/CityTourEiffelTower.png",
                                         text = {"The Great Pyramid of Giza (also known as the Pyramid ",
                                                  "of Khufu or the Pyramid of Cheops) is the oldest and largest of",
                                                  "the three pyramids in the Giza pyramid complex bordering what is",
                                                  "now El Giza, Egypt. It is the oldest one in the list of the Seven",
                                                  "Wonders of the Ancient World, and the only one to remain largely",
                                                  "intact. Based on a mark in an interior chamber naming the work",
                                                  "gang and a reference to fourth dynasty Egyptian Pharaoh Khufu,",
                                                  "Egyptologists believe that the pyramid was built as a tomb over a",
                                                  "10 to 20-year period concluding around 2560 BC."
                                                }
                                          },
                                          {name = "Egyptian museum",
                                          question = "How many objects were lost during the Egyptian revolution?",
                                          answers = {"50", "25", "60", "100"},
                                          pic_url = "data/images/CityTourEiffelTower.png",
                                          text = {"The Museum of Egyptian Antiquities, known commonly as the",
                                                   "Egyptian Museum or Museum of Cairo, in Cairo, Egypt, is home to",
                                                   "an extensive collection of ancient Egyptian antiquities. It has",
                                                   "120,000 items, with a representative amount on display, the",
                                                   "remainder in storerooms. During the Egyptian Revolution of 2011,",
                                                   "the museum was broken into, and two mummies were reportedly",
                                                   "destroyed. Several artifacts were also shown to have been damaged.",
                                                   "Around 50 objects were lost. Since then 25 objects have been found,",
                                                     "as of October 2015, it is open to the public."
                                                   }
                                          },
                                          {name = "Al-Azhar mosque",
                                          question = "What is the name of the prophet of Islam?",
                                          answers = {"Mohammad", "Ali", "Al-Azhar", "Fatimah"},
                                          pic_url = "data/images/CityTourEiffelTower.png",
                                          text = {"Al-Azhar (mosque of the most resplendent) is a mosque in Islamic",
                                                  "Cairo in Egypt. Al-Mu'izz li-Din Allah of the Fatimid Caliphate",
                                                  "commissioned its construction for the newly established capital city",
                                                  "in 970. Its name is usually thought to allude to the Islamic prophet",
                                                  "Muhammad's daughter Fatimah, a revered figure in Islam who was",
                                                  "given the title az-Zahrā′ (the shining or resplendent one). It was the",
                                                  "first mosque established in Cairo, a city that has since gained the",
                                                  "nickname the City of a Thousand Minarets."
                                                }
                                          },
                                          {name = "The Citadel",
                                          question = "What was the purpose of fortifying The Citadel?",
                                          answers = {"Protect it from the Crusaders", "Protect it from Thieves", "Make it look better", "Make it a prison"},
                                          pic_url = "data/images/CityTourEiffelTower.png",
                                          text = {"The Citadel was fortified by the Ayyubid ruler Salah al-Di (Saladin)",
                                                  "between 1176 and 1183 CE, to protect it from the Crusaders.",
                                                  "Only a few years after defeating the Fatimid Caliphate, Saladin",
                                                  "set out to build a wall that would surround both Cairo and Fustat.",
                                                  "Saladin is recorded as saying, With a wall I will make the two ",
                                                  "(cities of Cairo and Fustat) into a unique whole, so that one army ",
                                                  "may defend them both; and I believe it is good to encircle them",
                                                  "with a single wall from the bank of the Nile to the bank of the ",
                                                  "Nile”. The Citadel would be the centerpiece ofthe wall. It is now a",
                                                  "preserved historic site, with mosques and museums."
                                                }
                                          }
                                  }
                                }


return attractions
